# Equipamiento Urbano
## Ayuntamiento de Barcelona

In [307]:
import pandas as pd
import src.equipamiento as eq
import importlib
importlib.reload(eq)

## Cultura.
### centros civicos

In [232]:
civic = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\\2021_centres_civics_entitats.csv")

In [233]:
civic = eq.civic_ (civic)

In [235]:
civic

,name,district_id,district,barri_id,barri,latitud,longitud,total_usos_entitats,metres_quadrats
0,Centre Cívic Barceloneta,1,Ciutat Vella,3,la Barceloneta,41.380269,2.192301,130,1431
1,Centre Cívic Baró de Viver,9,Sant Andreu,58,Baró de Viver,41.448392,2.199921,39,1535
2,Centre Cívic Besòs,10,Sant Martí,70,el Besòs i el Maresme,41.416306,2.211479,0,3858
3,Centre Cívic Bon Pastor,9,Sant Andreu,59,el Bon Pastor,41.434780,2.204912,29,1370
4,Centre Cívic Can Basté,8,Nou Barris,46,el Turó de la Peira,41.430459,2.173212,54,1060
5,Centre Cívic Can Castelló,5,Sarrià-Sant Gervasi,26,Sant Gervasi - Galvany,41.399006,2.140163,17,1200
6,Centre Cívic Can Clariana Cultural,9,Sant Andreu,62,el Congrés i els Indians,41.427518,2.178412,72,842
7,Centre Cívic Can Deu,4,Les Corts,19,les Corts,41.386761,2.132502,0,803
8,Centre Cívic Can Felipa,10,Sant Martí,68,el Poblenou,41.404013,2.201387,72,3125
9,Centre Cívic Can Verdaguer,8,Nou Barris,45,Porta,41.433977,2.179080,52,990
10,Centre Cívic Casa del Rellotge,3,Sants-Montjuïc,13,la Marina de Port,41.357544,2.141390,32,880
11,Centre Cívic Casa Groga,7,Horta-Guinardó,39,Sant Genís dels Agudells,41.426863,2.137450,20,1152
12,Centre Cívic Casa Orlandai,5,Sarrià-Sant Gervasi,23,Sarrià,41.398330,2.124656,96,1066
13,Centre Cívic Convent de Sant Agustí,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",41.387391,2.181711,104,1655
14,Centre Cívic Cotxeres Borrell,2,Eixample,10,Sant Antoni,41.375909,2.163176,98,1775
15,Centre Cívic Cotxeres de Sants,3,Sants-Montjuïc,18,Sants,41.375264,2.136876,180,3167
16,Centre Cívic del Parc - Sandaru,10,Sant Martí,66,el Parc i la Llacuna del Poblenou,41.391719,2.184755,64,2000
17,Centre Cívic Drassanes,1,Ciutat Vella,1,el Raval,41.377645,2.172852,6,1074
18,Centre Cívic El Carmel,7,Horta-Guinardó,37,el Carmel,41.420264,2.151191,42,1054
19,Centre Cívic El Coll - La Bruguera,6,Gràcia,29,el Coll,41.418579,2.149897,0,1300
20,Centre Cívic El Sortidor,3,Sants-Montjuïc,11,el Poble Sec,41.372067,2.162532,119,905
21,Centre Cívic Font de la Guatlla,3,Sants-Montjuïc,14,la Font de la Guatlla,41.370560,2.147509,12,635
22,Centre Cívic Fort Pienc,2,Eixample,5,el Fort Pienc,41.395557,2.182446,114,1306
23,Centre Cívic Golferichs,2,Eixample,9,la Nova Esquerra de l'Eixample,41.380813,2.156392,46,1025
24,Centre Cívic Guinardó,7,Horta-Guinardó,35,el Guinardó,41.416056,2.173323,52,600
25,Centre Cívic Joan Oliver - Pere Quart,4,Les Corts,20,la Maternitat i Sant Ramon,41.379303,2.127758,45,2433
26,Centre Cívic Josep M. Trias i Peitx - Riera Bl...,4,Les Corts,20,la Maternitat i Sant Ramon,41.377780,2.121763,0,800
27,Centre Cívic l'Elèctric,5,Sarrià-Sant Gervasi,22,"Vallvidrera, el Tibidabo i les Planes",41.419138,2.097872,17,566
28,Centre Cívic La Cadena,3,Sants-Montjuïc,13,la Marina de Port,41.364156,2.139067,6,333
29,Centre Cívic La Casa Elizalde,2,Eixample,7,la Dreta de l'Eixample,41.394484,2.165881,52,1800
30,Centre Cívic La Sagrera,9,Sant Andreu,61,la Sagrera,41.423942,2.189139,12,903
31,Centre Cívic La Sedeta,6,Gràcia,32,el Camp d'en Grassot i Gràcia Nova,41.405549,2.167665,36,1287
32,Centre Cívic Matas i Ramis,7,Horta-Guinardó,43,Horta,41.432755,2.160711,17,637
33,Centre Cívic Navas,9,Sant Andreu,63,Navas,41.416905,2.184919,54,1200
34,Centre Cívic Pati Llimona,1,Ciutat Vella,2,el Barri Gòtic,41.381636,2.179176,30,1900
35,Centre Cívic Pere Pruna,5,Sarrià-Sant Gervasi,25,Sant Gervasi - la Bonanova,41.403182,2.131303,4,287
36,Centre Cívic Sagrada Família,2,Eixample,6,la Sagrada Família,41.405380,2.176760,33,1900
37,Centre Cívic Sant Andreu,9,Sant Andreu,60,Sant Andreu,41.430853,2.189401,15,900
38,Centre Cívic Sant Martí,10,Sant Martí,72,Sant Martí de Provençals,41.416622,2.198564,130,5470
39,Centre Cívic Sarrià,5,Sarrià-Sant Gervasi,23,Sarrià,41.393872,2.121164,0,1011
40,Centre Cívic Teixonera,7,Horta-Guinardó,38,la Teixonera,41.422638,2.144555,43,841
41,Centre Cívic Tomasa Cuevas - Les Corts,4,Les Corts,19,les Corts,41.384784,2.128318,47,1603
42,Centre Cívic Torre Llobeta,8,Nou Barris,44,Vilapicina i la Torre Llobeta,41.426897,2.173951,63,738
43,Centre Cívic Trinitat Vella,9,Sant Andreu,57,la Trinitat Vella,41.451619,2.191190,53,750
44,Centre Cívic Urgell,2,Eixample,9,la Nova Esquerra de l'Eixample,41.386861,2.152032,100,953
45,Centre Cívic Vallvidrera Vázquez Montalbán,5,Sarrià-Sant Gervasi,22,"Vallvidrera, el Tibidabo i les Planes",41.415364,2.102531,5,618
46,Centre Cívic Vil·la Florida,5,Sarrià-Sant Gervasi,25,Sant Gervasi - la Bonanova,41.405337,2.135294,22,1574
47,Centre Cívic Vil·la Urània,5,Sarrià-Sant Gervasi,27,el Putxet i el Farró,41.398643,2.142760,88,3415
48,Centre Cívic Zona Nord,8,Nou Barris,55,Ciutat Meridiana,41.461114,2.177397,47,2418
49,Centre Cultural Albareda,3,Sants-Montjuïc,11,el Poble Sec,41.374000,2.173269,203,1473
50,Centre Cultural la Farinera del Clot,10,Sant Martí,65,el Clot,41.404914,2.188443,84,2634

### restaurants

In [236]:
rest = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\\restaurants.csv")

In [237]:
rest = eq.clean_equipamientos (rest)

In [239]:
rest

,name,barri_id,barri,district_id,district,category,latitude,longitude,address
0,Restaurant Els Pollos de Llull *Ramon Turró,67,la Vila Olímpica del Poblenou,10,Sant Martí,Restaurants,41.391080,2.190942,C Ramon Turró 13
1,Restaurant La Royale,25,Sant Gervasi - la Bonanova,5,Sarrià-Sant Gervasi,Restaurants,41.403463,2.136026,Pl Camp 5
2,Restaurant Ca l'Isidre,1,el Raval,1,Ciutat Vella,Restaurants,41.375971,2.167983,C Flors 12
3,Bar Restaurant Baztan,8,l'Antiga Esquerra de l'Eixample,2,Eixample,Restaurants,41.393962,2.156358,C Balmes 147
4,Restaurant Maccabi,1,el Raval,1,Ciutat Vella,Restaurants,41.381461,2.172793,C Rambla 79
...,...,...,...,...,...,...,...,...,...
2586,Bar Neutral,26,Sant Gervasi - Galvany,5,Sarrià-Sant Gervasi,Restaurants,41.393553,2.138566,C Ganduxer 26
2587,Restaurant Khalijia Shisha,7,la Dreta de l'Eixample,2,Eixample,Restaurants,41.390253,2.170580,Carrer de Pau Claris 92
2588,Hamburgueseria Rock & Boom,31,la Vila de Gràcia,6,Gràcia,Restaurants,41.398400,2.159791,Carrer de Bonavista 21
2589,Restaurant Bo de Bernat,10,Sant Antoni,2,Eixample,Restaurants,41.380510,2.160515,C Comte d'Urgell 27
2590,Bar Restaurant Chamako,11,el Poble-sec,3,Sants-Montjuïc,Restaurants,41.373813,2.163556,Carrer de Margarit 18

### Museum libraries.

In [240]:
mus = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\museum_libraries.csv")

In [241]:
mus = eq.clean_equipamientos (mus)

In [243]:
mus = clean_ids (mus)

In [245]:
mus

,name,barri_id,barri,district_id,district,category,latitude,longitude,address
0,Biblioteca Joan Miró,9,la Nova Esquerra de l'Eixample,2,Eixample,Biblioteques,41.378848,2.149248,Carrer de Vilamarí 61
1,Biblioteca Joan Miró,9,la Nova Esquerra de l'Eixample,2,Eixample,Biblioteques municipals,41.378848,2.149248,Carrer de Vilamarí 61
2,Biblioteca Joan Miró,9,la Nova Esquerra de l'Eixample,2,Eixample,Sales d'estudi,41.378848,2.149248,Carrer de Vilamarí 61
3,Museu Futbol Club Barcelona President Núñez,20,la Maternitat i Sant Ramon,4,Les Corts,Museus,41.379091,2.120286,Carrer d'Arístides Maillol 12
4,Museu del Disseny de Barcelona,66,el Parc i la Llacuna del Poblenou,10,Sant Martí,Museus,41.402601,2.188050,Plaça de les Glòries Catalanes 37
...,...,...,...,...,...,...,...,...,...
456,Biblioteca Camp de l'Arpa - Caterina Albert,64,el Camp de l'Arpa del Clot,10,Sant Martí,Sales d'estudi,41.415797,2.182298,Carrer de la Indústria 295
457,CRAI - Biblioteca de Fons Antic,8,l'Antiga Esquerra de l'Eixample,2,Eixample,Sales d'estudi,41.386577,2.164030,G
458,Sala d'Estudi Montserrat Abelló - Les Corts,19,les Corts,4,Les Corts,Sales d'estudi,41.383731,2.135306,C Comtes de Bell-lloc 192
459,Biblioteca Marta Mata,23,Sarrià,5,Sarrià-Sant Gervasi,Biblioteques,41.397392,2.119283,C Domínguez i Miralles 1
460,EcoMuseu Urbà Gitano de Barcelona,1,el Raval,1,Ciutat Vella,Museus,41.379232,2.166539,Carrer de la Cera 10

### music and drinks. NOT

In [246]:
drinks = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\music_drinks.csv")

In [247]:
drinks = eq.clean_equipamientos (drinks)

In [249]:
drinks

,name,barri_id,barri,district_id,district,category,latitude,longitude,address
0,Karaoke Touch Music,67,la Vila Olímpica del Poblenou,10,Sant Martí,Karaokes,41.389967,2.196581,C Joan Miró 8
1,Cocteleria P41 Bar & Coctelarium,3,la Barceloneta,1,Ciutat Vella,Cocteleries,41.387113,2.196574,C Marina 19
2,Cocteleria P41 Bar & Coctelarium,3,la Barceloneta,1,Ciutat Vella,Xampanyeries,41.387113,2.196574,C Marina 19
3,Golden Shisha Lounge,26,Sant Gervasi - Galvany,5,Sarrià-Sant Gervasi,Discoteques,41.400357,2.141796,C Plató 13
4,Bar Marsella,1,el Raval,1,Ciutat Vella,Bars i pubs musicals,41.378278,2.171224,C Sant Pau 65
...,...,...,...,...,...,...,...,...,...
614,Cocteleria Nola,31,la Vila de Gràcia,6,Gràcia,Cocteleries,41.398079,2.159655,Carrer de Santa Teresa 1
615,Cocteleria Nola,31,la Vila de Gràcia,6,Gràcia,Xampanyeries,41.398079,2.159655,Carrer de Santa Teresa 1
616,Bar Soda bus & Verne,8,l'Antiga Esquerra de l'Eixample,2,Eixample,Cocteleries,41.392070,2.154656,Carrer d'Aribau 150
617,Bar Soda bus & Verne,8,l'Antiga Esquerra de l'Eixample,2,Eixample,Xampanyeries,41.392070,2.154656,Carrer d'Aribau 150
618,Bar Soda bus & Verne,8,l'Antiga Esquerra de l'Eixample,2,Eixample,Restaurants,41.392070,2.154656,Carrer d'Aribau 150

### cines

In [250]:
cine = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\cultura\cinema.csv")

In [251]:
cine = eq.clean_equipamientos (cine)

In [253]:
cine

,name,barri_id,barri,district_id,district,category,latitude,longitude,address
0,Auditòrium,2,el Barri Gòtic,1,Ciutat Vella,Auditoris,41.382838,2.176818,Pl Sant Jaume 4
1,Teatre,60,Sant Andreu,9,Sant Andreu,Teatres,41.435729,2.186494,C Pons i Gallarza 58
2,Sala de Cinema,1,el Raval,1,Ciutat Vella,Cinemes,41.376851,2.173408,Av Drassanes 14
3,Teatre,64,el Camp de l'Arpa del Clot,10,Sant Martí,Teatres,41.410450,2.182461,C Provença 591
4,Teatre Romea,1,el Raval,1,Ciutat Vella,Teatres,41.380585,2.171083,C Hospital 51
...,...,...,...,...,...,...,...,...,...
190,Auditòrium,4,"Sant Pere, Santa Caterina i la Ribera",1,Ciutat Vella,Auditoris,41.391283,2.181347,Pg Lluís Companys 18
191,Centre de les Arts Lliures,4,"Sant Pere, Santa Caterina i la Ribera",1,Ciutat Vella,Teatres,41.384998,2.182022,Carrer de la Seca 2
192,Teatre,10,Sant Antoni,2,Eixample,Teatres,41.377441,2.155998,C Rocafort 42
193,Teatre,16,la Bordeta,3,Sants-Montjuïc,Teatres,41.371054,2.131946,Rbla Badal 113
194,Club Onyric,11,el Poble-sec,3,Sants-Montjuïc,Teatres,41.374807,2.164728,Av Paral

## educacion.
### escuelas

In [254]:
schools = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\equipamiento\education.csv")

In [255]:
schools = eq.clean_equipamientos (schools)

In [256]:
schools = eq.clean_ids (schools)

In [257]:
schools

,name,barri_id,barri,district_id,district,category,latitude,longitude,address
1,Centre Educatiu Valldaura,52,la Prosperitat,8,Nou Barris,Ensenyament infantil (3-6 anys),41.442245,2.180029,C Santa Engràcia 110
2,Centre Educatiu Valldaura,52,la Prosperitat,8,Nou Barris,Educació primària,41.442245,2.180029,C Santa Engràcia 110
3,Centre Educatiu Valldaura,52,la Prosperitat,8,Nou Barris,Educació secundària,41.442245,2.180029,C Santa Engràcia 110
5,Centre Educatiu Vedruna Gràcia Barcelona,31,la Vila de Gràcia,6,Gràcia,Ensenyament infantil (3-6 anys),41.404718,2.151416,C Gran de Gràcia 234
6,Centre Educatiu Vedruna Gràcia Barcelona,31,la Vila de Gràcia,6,Gràcia,Educació primària,41.404718,2.151416,C Gran de Gràcia 234
...,...,...,...,...,...,...,...,...,...
2664,Escola de Doctorat - UB,10,Sant Antoni,2,Eixample,Universitats,41.384856,2.162637,Gran Via de les Corts Catalanes 582
2665,Institut de Biologia Evolutiva,3,la Barceloneta,1,Ciutat Vella,Universitats,41.385565,2.193994,Carrer del Doctor Aiguader 88
2669,Nuclio Digital School,6,la Sagrada Família,2,Eixample,Informàtica,41.407147,2.175102,Carrer de Padilla 285
2672,Llar d'Infants El Camí Feliç ZAL Port,12,la Marina del Prat Vermell,3,Sants-Montjuïc,Ensenyament infantil (0-3 anys),41.322168,2.134977,Avinguda dels Ports d'Europa 90
2678,Llar d'Infants Kasperle,31,la Vila de Gràcia,6,Gràcia,Ensenyament infantil (0-3 anys),41.400944,2.154074,C Gran de Gràcia 97

### hospitals

In [258]:
hospitals = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\equipamiento\hospitals.csv")

In [259]:
hospitals = eq.clean_equipamientos (hospitals)

In [261]:
hospitals

,name,barri_id,barri,district_id,district,category,latitude,longitude,address
0,Hospital El Pilar - Institut Cardiovascular Sa...,26,Sant Gervasi - Galvany,5,Sarrià-Sant Gervasi,Hospitals i clíniques,41.400457,2.148500,C Balmes 271
1,Centre d'Atenció Primària Vallvidrera,22,"Vallvidrera, el Tibidabo i les Planes",5,Sarrià-Sant Gervasi,CAPs,41.413818,2.104164,Carrer d'Elisa Moragas i Badia 2
2,Centre d'Atenció Primària Turó,46,el Turó de la Peira,8,Nou Barris,CAPs,41.433082,2.170579,C Cadí 58
3,Centre d'Atenció Primària El Clot,65,el Clot,10,Sant Martí,CAPs,41.411767,2.193049,C Concili de Trento 25
4,Clínica Sant Antoni,13,la Marina de Port,3,Sants-Montjuïc,Hospitals i clíniques,41.356077,2.143294,C Sant Eloi 6
...,...,...,...,...,...,...,...,...,...
137,Centre d'Urgències d'Atenció Primària Horta,43,Horta,7,Horta-Guinardó,Centres urgències (CUAPs),41.434841,2.157430,C Sant Gaudenci 21
138,Centre d'Atenció Primària Casernes,60,Sant Andreu,9,Sant Andreu,CAPs,41.443165,2.192838,C Fernando Pessoa 51
139,Clínica Oftalvist,24,les Tres Torres,5,Sarrià-Sant Gervasi,Hospitals i clíniques,41.401070,2.125112,Carrer d'Anglí 38
140,Centre Mèdic Vilasalut *Barcelona,23,Sarrià,5,Sarrià-Sant Gervasi,Hospitals i clíniques,41.400146,2.119736,Sagrat Cor 7
141,Clínica Cipsalut,9,la Nova Esquerra de l'Eixample,2,Eixample,Hospitals i clíniques,41.381837,2.155480,Carrer de la Diputació 95

## SPORT
### excersice

In [308]:
exc = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\sports\excersice.csv")

In [309]:
exc = eq.clean_excersice (exc)

In [310]:
exc

,name,barri_id,barri,district_id,district,category,latitude,longitude,address
0,Àrea Esportiva,43,Horta,7,Horta-Guinardó,excersice,41.436303,2.157824,C Lloret de Mar 81
1,Àrea Esportiva *Pardo - Can Ros - Concepció Ar...,62,el Congrés i els Indians,9,Sant Andreu,excersice,41.426917,2.183275,C Can Ros 41
2,Àrea Esportiva,68,el Poblenou,10,Sant Martí,excersice,41.394603,2.206754,Pg Marítim del Bogatell 80
3,Espai Gimnàstic per a Gent Gran *Pujalt,56,Vallbona,8,Nou Barris,excersice,41.462926,2.182649,C Pujalt 5
4,Espai Gimnàstic per a Gent Gran *Jocs Esportiu...,69,Diagonal Mar i el Front Marítim del Poblenou,10,Sant Martí,excersice,41.410381,2.212477,C Pujades 402
5,Espai Gimnàstic per a Gent Gran,13,la Marina de Port,3,Sants-Montjuïc,excersice,41.359406,2.142822,C Mare de Déu de Port 172
6,Espai Gimnàstic per a Gent Gran *Plaça Navas,11,el Poble-sec,3,Sants-Montjuïc,excersice,41.374069,2.159467,Pl Las Navas 4
7,Espai Gimnàstic per a Gent Gran,3,la Barceloneta,1,Ciutat Vella,excersice,41.382060,2.193840,Pg Marítim de la Barceloneta 15
8,Espai Gimnàstic per a Gent Gran,32,el Camp d'en Grassot i Gràcia Nova,6,Gràcia,excersice,41.404604,2.169292,Carrer de Sicília 287
9,Espai Gimnàstic per a Gent Gran *Parc Sanitar...,28,Vallcarca i els Penitents,6,Gràcia,excersice,41.414955,2.140266,C Esteve Terradas 30
10,Espai Gimnàstic per a Gent Gran,33,el Baix Guinardó,7,Horta-Guinardó,excersice,41.409781,2.167751,C Marina 380
11,Espai Gimnàstic per a Gent Gran,20,la Maternitat i Sant Ramon,4,Les Corts,excersice,41.378964,2.116944,C Cardenal Reig 35
12,Espai Gimnàstic per a Gent Gran *Arc de Teatre,1,el Raval,1,Ciutat Vella,excersice,41.377218,2.174119,C Arc del Teatre 20
13,Espai Gimnàstic per a Gent Gran,43,Horta,7,Horta-Guinardó,excersice,41.433612,2.153300,Av Estatut de Catalunya 20
14,Espai Gimnàstic per a Gent Gran *Zona Esporti...,55,Ciutat Meridiana,8,Nou Barris,excersice,41.459543,2.175067,Av Rasos de Peguera 55
15,Espai Gimnàstic per a Gent Gran,44,Vilapicina i la Torre Llobeta,8,Nou Barris,excersice,41.427716,2.175718,C Costa i Cuxart 20
16,Espai Gimnàstic per a Gent Gran,10,Sant Antoni,2,Eixample,excersice,41.377713,2.163184,C Comte Borrell 44
17,Espai Gimnàstic per a Gent Gran * Conca de Tre...,37,el Carmel,7,Horta-Guinardó,excersice,41.424218,2.154701,C Conca de Tremp 6
18,Espai Gimnàstic per a Gent Gran,23,Sarrià,5,Sarrià-Sant Gervasi,excersice,41.393906,2.121187,C Eduardo Conde 22
19,Espai Gimnàstic per a Gent Gran *Pl del Mar,3,la Barceloneta,1,Ciutat Vella,excersice,41.373300,2.188414,Pl Mar 4
20,Espai Gimnàstic per a Gent Gran,46,el Turó de la Peira,8,Nou Barris,excersice,41.433467,2.163457,Pg Fabra i Puig 396
21,Espai Gimnàstic per a Gent Gran *Via Favència ...,57,la Trinitat Vella,9,Sant Andreu,excersice,41.448025,2.191972,Via Bàrcino 104
22,Espai Gimnàstic per a Gent Gran *Pl Assemblea...,61,la Sagrera,9,Sant Andreu,excersice,41.424931,2.188135,C Antilles 11
23,Espai Gimnàstic per a Gent Gran *Plaça Alta d...,13,la Marina de Port,3,Sants-Montjuïc,excersice,41.361736,2.146586,Pl Alta de Can Clos nan
24,Àrea Esportiva,67,la Vila Olímpica del Poblenou,10,Sant Martí,excersice,41.391413,2.204202,Pg Marítim de Nova Icària 60
25,Àrea Esportiva,6,la Sagrada Família,2,Eixample,excersice,41.404418,2.173147,Ptge Simó 9
26,Espai Gimnàstic per a Gent Gran *Perea - Vall ...,39,Sant Genís dels Agudells,7,Horta-Guinardó,excersice,41.424263,2.141226,C Perea 1
27,Espai Gimnàstic per a Gent Gran *Plaça Mainada,63,Navas,9,Sant Andreu,excersice,41.419566,2.183727,Pl Mainada 1
28,Espai Gimnàstic per a Gent Gran,60,Sant Andreu,9,Sant Andreu,excersice,41.440870,2.189750,C Valentí Iglésias 19
29,Espai Gimnàstic per a Gent Gran,25,Sant Gervasi - la Bonanova,5,Sarrià-Sant Gervasi,excersice,41.408846,2.136909,Ptge Maluquer 8
30,Espai Gimnàstic per a Gent Gran *Espigó del Gas,3,la Barceloneta,1,Ciutat Vella,excersice,41.381317,2.196567,Pg Marítim de la Barceloneta 21
31,Espai Gimnàstic per a Gent Gran,8,l'Antiga Esquerra de l'Eixample,2,Eixample,excersice,41.389056,2.150648,C Rosselló 149
32,Espai Gimnàstic per a Gent Gran *Plaça Palestina,39,Sant Genís dels Agudells,7,Horta-Guinardó,excersice,41.424754,2.139045,C Sinaí 6
33,Espai Gimnàstic per a Gent Gran *Pl Carmen La...,44,Vilapicina i la Torre Llobeta,8,Nou Barris,excersice,41.426916,2.176470,Pl Carmen Laforet 10
34,Espai Gimnàstic per a Gent Gran,68,el Poblenou,10,Sant Martí,excersice,41.406111,2.201844,Camí Antic de València 63
35,Espai Gimnàstic per a Gent Gran *Av Bogatell,67,la Vila Olímpica del Poblenou,10,Sant Martí,excersice,41.393020,2.196717,Av Bogatell 24
36,Espai Gimnàstic per a Gent Gran,6,la Sagrada Família,2,Eixample,excersice,41.404098,2.179799,C Padilla 210
37,Espai Gimnàstic per a Gent Gran,29,el Coll,6,Gràcia,excersice,41.419264,2.146252,Pg Mare de Déu del Coll 77
38,Espai Gimnàstic per a Gent Gran *Plaça de les ...,41,la Vall d'Hebron,7,Horta-Guinardó,excersice,41.432256,2.147394,C Jorge Manrique 28

### pools.

In [323]:
pool = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\sports\pools.csv")

In [284]:
pool = eq.clean_pool (pool)

In [285]:
pool

,name,barri_id,barri,district_id,district,latitude,longitude,address
0,Piscina Coberta Pere Serrat,60,Sant Andreu,9,Sant Andreu,41.430050,2.186313,Rbla Fabra i Puig 47
1,Piscina Esportiva Descoberta,28,Vallcarca i els Penitents,6,Gràcia,41.422215,2.137778,Ctra Sant Cugat 97
2,Piscina Descoberta,20,la Maternitat i Sant Ramon,4,Les Corts,41.383512,2.109679,Av Diagonal 671
3,Centre Esportiu Municipal Can Caralleu,23,Sarrià,5,Sarrià-Sant Gervasi,41.400987,2.110505,Carrer dels Esports 2
4,Piscina Descoberta,41,la Vall d'Hebron,7,Horta-Guinardó,41.429575,2.145185,Pg Vall d'Hebron 178
...,...,...,...,...,...,...,...,...
126,Piscina Clapoteig Coberta,20,la Maternitat i Sant Ramon,4,Les Corts,41.386560,2.123127,Pl Pius XII 4
127,Piscina Descoberta,11,el Poble-sec,3,Sants-Montjuïc,41.368531,2.146186,Foixarda 2
128,Piscina Esportiva Descoberta,21,Pedralbes,4,Les Corts,41.393690,2.118332,Bosch i Gimpera 5
129,Piscines Cobertes,70,el Besòs i el Maresme,10,Sant Martí,41.412015,2.213230,C Puigcerdà 61
130,Piscina Descoberta,4,"Sant Pere, Santa Caterina i la Ribera",1,Ciutat Vella,41.385203,2.186629,Pg Circumval

### walk circuit

In [320]:
walk = pd.read_csv("D:\ironhack\proyectos\Barcelona_UrbanAnalysis\csv\sports\walk_run_circuits.csv")

In [321]:
walk = eq.clean_pool (walk)

In [322]:
walk

,name,barri_id,barri,district_id,district,latitude,longitude,address
0,Circuit Esportiu Castell de Montjuïc *circuit 1,11,el Poble-sec,3,Sants-Montjuïc,41.364692,2.166034,Ctra Montjuïc 60
1,Circuit Esportiu Aragó - Guipúscoa,65,el Clot,10,Sant Martí,41.408697,2.187242,C Aragó 602
2,Circuit Esportiu,4,"Sant Pere, Santa Caterina i la Ribera",1,Ciutat Vella,41.385711,2.185848,Pg Picasso 21
3,Circuit Esportiu Mirador de les Aigües,21,Pedralbes,4,Les Corts,41.393841,2.098001,Ctra Aigües 1
4,Circuit Esportiu Passeig Marítim,67,la Vila Olímpica del Poblenou,10,Sant Martí,41.389928,2.200425,C Arquitecte Sert 1
5,Circuit de Fitness del Parc del Litoral,69,Diagonal Mar i el Front Marítim del Poblenou,10,Sant Martí,41.397978,2.211276,Pg Marítim de la Mar Bella 104
6,Circuit Esportiu Diagonal - Sant Martí,66,el Parc i la Llacuna del Poblenou,10,Sant Martí,41.403716,2.188941,Av Diagonal 211
7,Circuit Esportiu,65,el Clot,10,Sant Martí,41.408472,2.190015,C Escultors Claperós 55
8,Circuit Esportiu Rambla Prim,73,la Verneda i la Pau,10,Sant Martí,41.425569,2.200423,Rbla Prim 256
9,Circuit Esportiu Diagonal - Cervantes,26,Sant Gervasi - Galvany,5,Sarrià-Sant Gervasi,41.392957,2.143527,Pl Francesc Macià 6
10,Circuit Esportiu,9,la Nova Esquerra de l'Eixample,2,Eixample,41.378847,2.149250,C Vilamarí 61
11,Circuit Esportiu Castell de Montjuïc *circuit 2,11,el Poble-sec,3,Sants-Montjuïc,41.364692,2.166034,Ctra Montjuïc 60
12,Circuit Esportiu Can Dragó,45,Porta,8,Nou Barris,41.431695,2.181443,Av Rio de Janeiro 2